### ISSUE TITLE
Using my own Audio stream to generate text from speech?

### ISSUE THREAD

**Issue by Monacraft** [puemos/speechless#50]
Works great in a webpage, but if I have my own audio stream (in a opus or pcm format), can I use speechless to convert the audio into speech.

If so, that would be great 💯 
Thank you 💓 

Sample code:
```js
let voiceReceiver = voiceConnection.createReceiver();
voiceReceiver.on('opus', (user, data) => {
    if(user === ..... ) { // Code to handle user etc. 
        // Use data to feed into the text to speech api
    }
});
```

**Comment by puemos** [comment]
@Monacraft thanks! :heartbeat:

**Speechless** is using [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) or external API such as [Google cloud speech](https://cloud.google.com/speech-to-text/) or [Amazon Transcribe](https://aws.amazon.com/blogs/aws/amazon-transcribe-scalable-and-accurate-automatic-speech-recognition/) so you can use one of these services for that.

hope I answered your question
